# Copyright 2025 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Eyelash Corne'
on: 
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["eyelash_corne_left", "eyelash_corne_right"]'
      shield: '["nice_view", "nice_view"]'