# Copyright 2025 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Build Eyelash Corne"
on: workflow_dispatch
jobs:
  build-left:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["eyelash_corne_left"]'
      shield: '["nice_view"]'
      modules: '["a741725193/zmk-new_corne/main"]'
      kconfig: '["CONFIG_ZMK_STUDIO=y\nCONFIG_ZMK_STUDIO_LOCKING=n\nCONFIG_ZMK_MOUSE=n\nCONFIG_ZMK_POINTING=y"]'
      snippet: '["studio-rpc-usb-uart"]'
  build-right:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["eyelash_corne_right"]'
      shield: '["nice_view_custom"]'
      modules: '["a741725193/zmk-new_corne/main"]'
      kconfig: '["CONFIG_ZMK_MOUSE=n\nCONFIG_ZMK_POINTING=y"]'
