# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build eyelash_corne'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["eyelash_corne_left", "eyelash_corne_right"]'
      shield: '["nice_view"]'
      alphas: '["qwerty"]'
      nav: '["vi"]'
      modules: '["a741725193/zmk-new_corne/main"]'
      kconfig: '["CONFIG_ZMK_POINTING=y"]'
